name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake .
    - name: cmake build
      run: cmake --build .
      
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt-get install libxcursor-dev
    - name: cmake configure
      run: |
        cd gwen
        cmake .
    - name: cmake build
      run: |
        cd gwen
        cmake --build .
